{{- if .Values.doppler.enabled }}
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: {{ include "main-api.fullname" . }}-doppler # Name of the DopplerSecret resource
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "main-api.labels" . | nindent 4 }}
spec:
 
  tokenSecret:
    name: {{ required "Doppler tokenSecretName is required when doppler is enabled" .Values.doppler.tokenSecretName }}
 
  managedSecret:
    name: {{ required "Doppler managedSecretName is required when doppler is enabled" .Values.doppler.managedSecretName }}
  project: {{ required "Doppler projectName is required when doppler is enabled" .Values.doppler.projectName }}
 
  config: {{ .Values.doppler.configName | default .Values.global.dopplerConfigName | required "Doppler configName or global.dopplerConfigName is required" }}
{{- end }} 