apiVersion: v1
kind: Service
metadata:
  name: {{ include "main-api.fullname" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "main-api.labels" . | nindent 4 }}
spec:
  #type: {{ .Values.service.type }}
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    # - port: {{ .Values.service.port }}
    #   targetPort: {{ .Values.service.targetPort }}
    - port: {{ .Values.service.port | default 8080 | int }}
      targetPort: {{ .Values.service.targetPort | default 8080 }} # Can be number or name (e.g., 'http')
      protocol: TCP
      name: http # Name of the port
  selector:
    {{- include "main-api.selectorLabels" . | nindent 4 }} 