# Global settings shared across all sub-charts
global:
  # Deployment mode: "local" or "cluster"
  deploymentMode: "local"
  
  # Environment name (overridden in environment-specific values files)
  environment: "dev"
  
  # Default storage class (overridden in environment-specific values files)
  storageClass: "standard"
  
  # OCI-specific configuration (used in cluster mode)
  oci:
    enabled: false
    region: ""
    compartmentId: ""
    availabilityDomains:
      - ""
    faultDomains:
      - ""
    # Default instance shape for compute
    instanceShape: "VM.Standard.E3.Flex"
    # Default flexible shape configuration
    flexShape:
      ocpus: 1
      memoryInGBs: 16
  
  # Doppler configuration
  doppler:
    enabled: true  # Enable Doppler
    # Default token secret name (can be overridden per service)
    tokenSecret: "doppler-token-secret"
    # Default project name (can be overridden per service)
    project: "koci"
    # Default naming pattern for managed secrets
    secretNamePattern: "%s-doppler-secrets-%s" # args: service name, environment
  
  # Image pull secrets (if needed)
  imagePullSecrets: []
  
  # Database configuration defaults
  databases:
    # MySQL configuration - DISABLED
    mysql:
      selfHosted:
        enabled: false  # Disable MySQL
        persistence:
          size: 2Gi
        auth:
          rootPasswordSecretKey: MYSQL_ROOT_PASSWORD
          userSecretKey: MYSQL_USER
          passwordSecretKey: MYSQL_PASSWORD
      managed:
        enabled: false
        host: ""
        port: 3306
        credentialsSecretName: ""
        usernameKey: "username"
        passwordKey: "password"
    
    # MongoDB configuration - ENABLED
    mongodb:
      selfHosted:
        enabled: true  # Enable MongoDB
        persistence:
          size: 5Gi  # Increased size for production use
        auth:
          rootUserSecretKey: MONGO_INITDB_ROOT_USERNAME
          rootPasswordSecretKey: MONGO_INITDB_ROOT_PASSWORD
        # OCI-specific settings for MongoDB
        oci:
          faultDomain: ""
      backup:
        enabled: true  # Enable MongoDB backup
        schedule: "0 2 * * *"  # Daily at 2 AM
        storageClass: ""
        retention: 7  # Keep backups for 7 days
        # OCI Object Storage for backups
        objectStorage:
          enabled: false
          bucketName: ""
          region: ""
          credentialsSecretName: ""
  
  # Cache configuration - ENABLED
  cache:
    redis:
      selfHosted:
        enabled: true  # Enable Redis
        persistence:
          size: 2Gi
        # OCI-specific settings for Redis
        oci:
          faultDomain: ""
      managed:
        enabled: false
        host: ""
        port: 6379
        credentialsSecretName: ""
  
  # Messaging configuration - ENABLED
  messaging:
    rabbitmq:
      selfHosted:
        enabled: true  # Enable RabbitMQ
        persistence:
          size: 2Gi
        # OCI-specific settings for RabbitMQ
        oci:
          faultDomain: ""
      managed:
        enabled: false
        host: ""
        port: 5672
        credentialsSecretName: ""
        usernameKey: "username"
        passwordKey: "password"

# Service configurations - ALL DISABLED
mainApi:
  enabled: false  # Disable main-api service
  replicaCount: 1
  autoscaling:
    enabled: false
  networkPolicy:
    enabled: false
  doppler:
    enabled: false
    projectName: "main-api"
    tokenSecretName: "main-api-doppler-token-secret"
    managedSecretName: ""
    annotations: {}

authServer:
  enabled: false  # Disable auth-server service
  replicaCount: 1
  autoscaling:
    enabled: false
  networkPolicy:
    enabled: false
  doppler:
    enabled: false
    projectName: "auth-server"
    tokenSecretName: "auth-server-doppler-token-secret"
    managedSecretName: ""
    annotations: {}

notificationService:
  enabled: false  # Disable notification-service
  replicaCount: 1
  autoscaling:
    enabled: false
  networkPolicy:
    enabled: false
  persistence:
    enabled: true
    size: 1Gi
  doppler:
    enabled: false
    projectName: "notification-service"
    tokenSecretName: "notification-service-doppler-token-secret"
    managedSecretName: ""
    annotations: {}

# Database configurations (defaults for internal deployments)
mongodb:
  internal:
    enabled: true  # Enable internal MongoDB
  external:
    enabled: false
    host: ""
    port: 27017
  database: "koci"
  existingSecret: ""

mysql:
  internal:
    enabled: false  # Disable internal MySQL
    auth:
      rootPasswordSecretKey: MYSQL_ROOT_PASSWORD
      userSecretKey: MYSQL_USER
      passwordSecretKey: MYSQL_PASSWORD
  external:
    enabled: false
    host: ""
    port: 3306
  database: "koci"
  existingSecret: ""
  ssl:
    enabled: false
    mode: "VERIFY_CA"
    caKey: "OCI_MYSQL_CA_CERT"

# Cache configuration
redis:
  internal:
    enabled: true  # Enable internal Redis
    auth:
      enabled: true
      passwordSecretKey: REDIS_PASSWORD
    persistence:
      enabled: true  # Enable persistence for Redis
  external:
    enabled: false
    host: ""
    port: 6379
  existingSecret: ""

# Messaging configuration
rabbitmq:
  enabled: true  # Enable RabbitMQ
  cluster:
    replicas: 1
    persistence:
      enabled: true
      storage: 2Gi
    auth:
      usernameSecretKey: RABBITMQ_USERNAME
      passwordSecretKey: RABBITMQ_PASSWORD
    service:
      port: 5672
      managementPort: 15672
  connection:
    internal:
      enabled: true
    external:
      enabled: false
      host: ""
      port: 5672
  vhost: "/"
  existingSecret: ""

# Secrets Operator configuration - ENABLED
dopplerOperator:
  install: true  # Enable Doppler Operator installation
  serviceAccount:
    create: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# MongoDB backup job configuration
mongodb-backup:
  enabled: true  # Enable MongoDB backup job
  nameOverride: "mongodb-backup"
  fullnameOverride: "mongodb-backup"
  
  backup:
    image:
      repository: bitnami/mongodb
      tag: "6.0"  # Updated to match MongoDB version
    
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi

# Default resource profiles
resources:
  small:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  medium:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 400m
      memory: 512Mi
  large:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

# Default persistence configuration
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  ephemeral: false

# Default network policy configuration
networkPolicy:
  enabled: false
  ingress:
    enabled: true
    from: []
  egress:
    enabled: true
    rules: []