# Environment: Staging - CORRECTED VERSION
global:
  deploymentMode: "cluster"
  environment: staging
  storageClass: "oci-bv"  # ✅ FIXED: Use working storage class
  
  oci:
    enabled: true
    region: "us-ashburn-1"
  
  doppler:
    enabled: true
    project: "koci"
    tokenSecret: "doppler-token-secret"
  
  databases:
    mysql:
      selfHosted:
        enabled: false
      managed:
        enabled: false
    
    mongodb:
      selfHosted:
        enabled: true
        replicaCount: 3
        persistence:
          storageClass: "oci-bv"  # ✅ FIXED
          size: 50Gi
        auth:
          rootUserSecretKey: MONGODB_ROOT_USERNAME
          rootPasswordSecretKey: MONGODB_ROOT_PASSWORD
      backup:
        enabled: true
        schedule: "0 2 * * *"
        retention: 14
        storageClass: "oci-bv"  # ✅ FIXED
  
  cache:
    redis:
      selfHosted:
        enabled: true
        persistence:
          size: 10Gi
          storageClass: "oci-bv"  # ✅ FIXED
  
  messaging:
    rabbitmq:
      selfHosted:
        enabled: true
        persistence:
          size: 10Gi
          storageClass: "oci-bv"  # ✅ FIXED

# Disable all application services
mainApi:
  enabled: false
authServer:
  enabled: false
notificationService:
  enabled: false

# MongoDB configuration
mongodb:
  internal:
    enabled: true
  external:
    enabled: false
  replicaCount: 3
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 1
      memory: 2Gi
  persistence:
    enabled: true
    storageClass: "oci-bv"  # ✅ FIXED
    size: 50Gi

# Redis configuration
redis:
  internal:
    enabled: true
  external:
    enabled: false
  replicaCount: 1
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  persistence:
    enabled: true
    storageClass: "oci-bv"  # ✅ FIXED
    size: 10Gi

# RabbitMQ configuration (already working)
rabbitmq:
  enabled: true
  cluster:
    replicas: 3
    persistence:
      enabled: true
      storage: 10Gi
      storageClass: "oci-bv"  # Already correct
    auth:
      usernameSecretKey: RABBITMQ_USERNAME
      passwordSecretKey: RABBITMQ_PASSWORD
    service:
      port: 5672
      managementPort: 15672
  connection:
    internal:
      enabled: true
    external:
      enabled: false

# Doppler Operator configuration
dopplerOperator:
  install: true
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

# MongoDB backup job
mongodb-backup:
  enabled: true
  backup:
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi

# Staging-specific settings
persistence:
  enabled: true
  storageClass: "oci-bv"  # ✅ FIXED

networkPolicy:
  enabled: true