# Default values for RabbitMQ
# This is a YAML-formatted file.

image:
  repository: rabbitmq
  tag: 3.9.13-management
  pullPolicy: IfNotPresent

# Number of RabbitMQ replicas
replicaCount: 1

# RabbitMQ configuration
config:
  enableManagement: true
  enableMetrics: false
  memoryHighWatermark: 0.4
  diskFreeLimit: "50MB"

# Service configuration
service:
  type: ClusterIP
  amqpPort: 5672
  managementPort: 15672

# Persistence configuration
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: ""

# Resources configuration
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 400m
    memory: 512Mi

# Pod security context
securityContext:
  enabled: true
  fsGroup: 999
  runAsUser: 999

# Container security context
containerSecurityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 999

# Liveness probe
livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 30
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 3

# Readiness probe
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

# Pod disruption budget
podDisruptionBudget:
  enabled: false
  minAvailable: 1

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Clustering
clustering:
  enabled: false
  replicaCount: 3


cluster:
  name: "koci-rabbitmq-cluster" # Default cluster name
  replicas: 1
  image:
    repository: rabbitmq
    tag: "3.11-management"
  persistence:
    storage: 10Gi

  auth:
    usernameSecretKey: RABBITMQ_USERNAME
    passwordSecretKey: RABBITMQ_PASSWORD

  service:
    port: 5672
    managementPort: 15672


# Add other RabbitMQ cluster configurations as needed (plugins, policies, resources, etc.)
resources: {} 

# Doppler configuration (add this section)
doppler:
  enabled: false
  projectName: "oci-infra"
  tokenSecretName: "doppler-token-secret"
  managedSecretName: "rabbitmq-doppler-secrets"

# Authentication (add this section if not exists)
auth:
  username: "admin"
  password: ""  
  existingSecret: ""

# Existing secret configuration
existingSecret: ""