{{- if and .Values.global.oci.enabled .Values.global.oci.credentialProvider.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-credential-provider-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry-auth
data:
  credential-provider-config.yaml: |
    apiVersion: kubelet.config.k8s.io/v1
    kind: CredentialProviderConfig
    providers:
      - name: credential-provider-oke
        apiVersion: credentialprovider.kubelet.k8s.io/v1
        matchImages:
          - "*.ocir.io"
          {{- if .Values.global.oci.registry.server }}
          - "{{ .Values.global.oci.registry.server }}/*"
          {{- end }}
        defaultCacheDuration: {{ .Values.global.oci.credentialProvider.cacheDuration | default "55m" }}
        env:
          - name: REGISTRY_TOKEN_PATH
            value: {{ .Values.global.oci.credentialProvider.tokenPath | default "/20180419/docker/token" }}
          - name: DEFAULT_USER
            value: {{ .Values.global.oci.credentialProvider.defaultUser | default "BEARER_TOKEN" }}
          - name: REGISTRY_PROTOCOL
            value: {{ .Values.global.oci.credentialProvider.protocol | default "https" }}
          - name: OCIR_AUTH_METHOD
            value: {{ .Values.global.oci.credentialProvider.authMethod | default "INSTANCE_PRINCIPAL" }}
          - name: TOKEN_VALIDATION
            value: {{ .Values.global.oci.credentialProvider.tokenValidation | default "enabled" }}
{{- end }}
