{{- if .Values.global.imagePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: ocir-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .Values.global.oci.registry.server .Values.global.oci.registry.username .Values.global.oci.registry.password .Values.global.oci.registry.email (printf "%s:%s" .Values.global.oci.registry.username .Values.global.oci.registry.password | b64enc) | b64enc }}
{{- end }} 