{{- if and .Values.global.oci.enabled .Values.global.oci.credentialProvider.enabled }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-oke-credential-provider-installer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: credential-provider-installer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: oke-credential-provider-installer
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oke-credential-provider-installer
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        configmap/checksum: {{ include (print $.Template.BasePath "/credential-provider-config.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ .Release.Name }}-registry-sa
      hostNetwork: true
      hostPID: true
      tolerations:
        - operator: Exists
      initContainers:
        - name: setup-credential-provider
          image: busybox:1.35
          command:
            - /bin/sh
            - -c
            - |
              set -e
              
              echo "=== OKE Credential Provider Setup Started ==="
              echo "Node: $(hostname)"
              echo "Architecture: $(uname -m)"
              echo "Date: $(date)"
              
              # Create directories if they don't exist
              echo "Creating directories..."
              mkdir -p /host/usr/local/bin
              mkdir -p /host/etc/kubernetes
              
              # Detect architecture
              if [ "$(uname -m)" = "aarch64" ]; then
                ARCH="arm64"
              else
                ARCH="amd64"
              fi
              echo "Detected architecture: $ARCH"
              
              # Check if binary already exists and is recent
              BINARY_PATH="/host/usr/local/bin/credential-provider-oke"
              DOWNLOAD_BINARY=true
              
              if [ -f "$BINARY_PATH" ]; then
                echo "Binary exists, checking age..."
                # Check if binary is less than 24 hours old
                if find "$BINARY_PATH" -mtime -1 2>/dev/null | grep -q .; then
                  echo "Binary exists and is recent, skipping download"
                  DOWNLOAD_BINARY=false
                else
                  echo "Binary exists but is old, will re-download"
                fi
              else
                echo "Binary does not exist, will download"
              fi
              
              if [ "$DOWNLOAD_BINARY" = "true" ]; then
                echo "Downloading OKE credential provider for $ARCH..."
                
                # Test network connectivity first
                echo "Testing network connectivity..."
                if ! wget -q --timeout=10 --spider https://github.com 2>/dev/null; then
                  echo "ERROR: Cannot reach github.com"
                  echo "Network connectivity test failed"
                  exit 1
                fi
                echo "Network connectivity OK"
                
                cd /tmp
                
                # Download with retry logic
                RETRY_COUNT=0
                MAX_RETRIES=5
                DOWNLOAD_URL="https://github.com/oracle-devrel/oke-credential-provider-for-ocir/releases/latest/download/oke-credential-provider-for-ocir-linux-$ARCH"
                
                echo "Download URL: $DOWNLOAD_URL"
                
                while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
                  echo "Download attempt $((RETRY_COUNT + 1))/$MAX_RETRIES..."
                  
                  if wget --progress=bar:force --timeout=60 --tries=1 \
                    "$DOWNLOAD_URL" \
                    -O "$BINARY_PATH" 2>&1; then
                    echo "Download successful!"
                    break
                  else
                    RETRY_COUNT=$((RETRY_COUNT + 1))
                    echo "Download failed, retry $RETRY_COUNT/$MAX_RETRIES"
                    if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
                      echo "Waiting 10 seconds before retry..."
                      sleep 10
                    fi
                  fi
                done
                
                if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
                  echo "ERROR: Failed to download binary after $MAX_RETRIES retries"
                  echo "This could be due to:"
                  echo "1. Network connectivity issues"
                  echo "2. GitHub rate limiting"
                  echo "3. Invalid architecture: $ARCH"
                  echo "4. Proxy/firewall blocking downloads"
                  exit 1
                fi
                
                # Verify download
                if [ ! -f "$BINARY_PATH" ]; then
                  echo "ERROR: Binary file was not created"
                  exit 1
                fi
                
                # Check file size
                FILE_SIZE=$(stat -c%s "$BINARY_PATH" 2>/dev/null || echo 0)
                if [ "$FILE_SIZE" -lt 1000000 ]; then
                  echo "ERROR: Downloaded file is too small ($FILE_SIZE bytes), likely corrupted"
                  rm -f "$BINARY_PATH"
                  exit 1
                fi
                
                echo "Download verified: $FILE_SIZE bytes"
                
                # Make it executable
                chmod 755 "$BINARY_PATH"
                echo "Binary made executable"
                
                # Verify binary is executable
                if [ ! -x "$BINARY_PATH" ]; then
                  echo "ERROR: Binary is not executable after chmod"
                  exit 1
                fi
                
                echo "Binary installation completed successfully"
              else
                echo "Using existing binary"
              fi
              
              # Verify configuration file exists
              if [ ! -f "/config/credential-provider-config.yaml" ]; then
                echo "ERROR: Configuration file not found in /config/"
                echo "Available files in /config/:"
                ls -la /config/ || echo "Cannot list /config/ directory"
                exit 1
              fi
              
              # Always update the configuration file
              echo "Copying credential provider configuration..."
              cp /config/credential-provider-config.yaml /host/etc/kubernetes/
              
              # Verify config was copied
              if [ ! -f "/host/etc/kubernetes/credential-provider-config.yaml" ]; then
                echo "ERROR: Configuration file was not copied successfully"
                exit 1
              fi
              
              echo "Configuration file copied successfully"
              echo "=== OKE Credential Provider Setup Completed Successfully ==="
              echo "Binary location: $BINARY_PATH"
              echo "Config location: /host/etc/kubernetes/credential-provider-config.yaml"
              echo "Setup completed at: $(date)"
          volumeMounts:
            - name: host-usr-local-bin
              mountPath: /host/usr/local/bin
            - name: host-etc-kubernetes
              mountPath: /host/etc/kubernetes
            - name: credential-provider-config
              mountPath: /config
          securityContext:
            privileged: true
      containers:
        - name: credential-provider-monitor
          image: busybox:1.35
          command:
            - /bin/sh
            - -c
            - |
              echo "OKE credential provider monitor started"
              echo "Monitoring credential provider binary and configuration..."
              
              while true; do
                # Check if binary exists and is executable
                if [ ! -x "/host/usr/local/bin/credential-provider-oke" ]; then
                  echo "WARNING: credential-provider-oke binary is missing or not executable"
                fi
                
                # Check if config exists
                if [ ! -f "/host/etc/kubernetes/credential-provider-config.yaml" ]; then
                  echo "WARNING: credential-provider-config.yaml is missing"
                fi
                
                sleep 300  # Check every 5 minutes
              done
          volumeMounts:
            - name: host-usr-local-bin
              mountPath: /host/usr/local/bin
              readOnly: true
            - name: host-etc-kubernetes
              mountPath: /host/etc/kubernetes
              readOnly: true
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 64Mi
      volumes:
        - name: host-usr-local-bin
          hostPath:
            path: /usr/local/bin
            type: DirectoryOrCreate
        - name: host-etc-kubernetes
          hostPath:
            path: /etc/kubernetes
            type: DirectoryOrCreate
        - name: credential-provider-config
          configMap:
            name: {{ .Release.Name }}-credential-provider-config
      nodeSelector:
        kubernetes.io/os: linux
{{- end }}
