# {{- if .Values.global.oci.enabled }}
# ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-registry-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry-auth
  annotations:
    # OCI Instance Principal annotation for container registry access
    oci.oraclecloud.com/instance-principal: "true"
    # Description
    description: "Service account for OCI container registry access using instance principal"
# {{- end }} 