apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-server.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "auth-server.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "auth-server.name" . }}
    spec:
      {{- if .Values.global.oci.enabled }}
      # Use registry service account for OCI instance principal authentication
      serviceAccountName: {{ .Release.Name }}-registry-sa
      {{- else }}
      {{- with .Values.global.imagePullSecrets }} # Use global imagePullSecrets
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "main-api.serviceAccountName" . }}
      {{- end }}
      containers:
        - name: {{ include "auth-server.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port | default 8080 | int }}
              name: http
          envFrom:
            - configMapRef:
                name: {{ include "auth-server.fullname" . }}-config
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
