apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth-server.fullname" . }}-config
  labels:
    {{- include "auth-server.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- if .Values.doppler.enabled }}
  K9_DOPPLER_PROJECT: {{ .Values.doppler.projectName }}
  K9_DOPPLER_CONFIG: {{ .Values.environment | default "dev" }}
  {{- end }}