apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: {{ include "auth-server.fullname" . }}-secrets
  annotations:
    {{- toYaml .Values.doppler.annotations | nindent 4 }}
spec:
  tokenSecret:
    name: {{ .Values.doppler.tokenSecretName }}
  managedSecret:
    name: {{ default (printf "%s-secrets" (include "auth-server.fullname" .)) .Values.doppler.managedSecretName }}
  project: {{ .Values.doppler.projectName }}
  config: {{ .Values.config.ENVIRONMENT | default "dev" }} 
  
