# charts/messaging/rabbitmq/templates/secret.yaml
{{- if not .Values.existingSecret }}
{{- if not (and .Values.doppler .Values.doppler.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.fullname" . }}-auth
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.cluster.auth.usernameSecretKey }}: {{ .Values.auth.username | default "admin" | b64enc }}
  {{ .Values.cluster.auth.passwordSecretKey }}: {{ .Values.auth.password | default (randAlphaNum 16) | b64enc }}
{{- end }}
{{- end }}