apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: mongodb-doppler-secret
  namespace: {{ .Values.global.doppler.operatorNamespace }}
  labels:
    app.kubernetes.io/name: {{ include "common.names.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: mongodb-secrets
spec:
  tokenSecret:
    name: {{ .Values.global.doppler.tokenSecretName }}
    namespace: {{ .Values.global.doppler.operatorNamespace }}
  managedSecret:
    name: koci-mongodb-secrets
    namespace: {{ .Release.Namespace }}
    type: Opaque
  project: {{ .Values.global.doppler.project }}
  config: {{ .Values.global.doppler.configName }}
  resyncSeconds: 120
