{{- if .Values.global.databases.mongodb.selfHosted.doppler.enabled }}
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: {{ include "mongodb.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  annotations:
    doppler.com/watch: "true"
    doppler.com/format: "env"
spec:
  # Reference the K8s secret holding the Doppler Service Token
  tokenSecret:
    name: {{ required "Doppler tokenSecretName is required when doppler is enabled" .Values.global.databases.mongodb.selfHosted.doppler.tokenSecretName }}
  # Name of the Kubernetes secret that Doppler Operator will create/manage
  managedSecret:
    name: {{ required "Doppler managedSecretName is required when doppler is enabled" .Values.global.databases.mongodb.selfHosted.doppler.managedSecretName }}
  project: {{ required "Doppler projectName is required when doppler is enabled" .Values.global.databases.mongodb.selfHosted.doppler.projectName }}
  # Use the config name from the global MongoDB Doppler configuration
  config: {{ required "Doppler configName is required" .Values.global.databases.mongodb.selfHosted.doppler.configName }}
  resyncSeconds: 120
{{- end }} 