apiVersion: v1
kind: Service
metadata:
  name: main-api-mongodb-service
spec:
  selector:
    app: main-api-mongodb
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "ClusterIP" }}
  clusterIP: None  # Headless service for internal access
  {{- end }}