{{- if not .Values.existingSecret }}
{{- if not (and .Values.doppler .Values.doppler.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}-secrets
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.auth.rootUser | default "admin" | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ randAlphaNum 16 | b64enc }}
{{- end }}
{{- end }}