{{- if not .Values.existingSecret }}
{{- if not (and .Values.doppler .Values.doppler.enabled) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}-secrets
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.auth.rootUser | default "admin" | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ randAlphaNum 16 | b64enc }}

  {{- if .Values.auth.replicaSetKey }}
  MONGO_REPLICA_SET_KEY: {{ .Values.auth.replicaSetKey | b64enc }}
  {{- else }}
  MONGO_REPLICA_SET_KEY: {{ randAlphaNum 756 | b64enc }}
  {{- end }}
{{- else if and .Values.doppler .Values.doppler.enabled }}
# Create fallback secret when Doppler is enabled but managed secret doesn't exist
# This ensures MongoDB can start even if Doppler Operator fails
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.doppler.managedSecretName | default "koci-mongodb-secrets" }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
    app.kubernetes.io/component: "mongodb-fallback-secret"
    doppler.com/fallback: "true"
  annotations:
    doppler.com/fallback-secret: "true"
    doppler.com/managed-secret-name: {{ .Values.doppler.managedSecretName | default "koci-mongodb-secrets" }}
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.auth.rootUser | default "admin" | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ randAlphaNum 16 | b64enc }}
  {{- if .Values.auth.replicaSetKey }}
  MONGO_REPLICA_SET_KEY: {{ .Values.auth.replicaSetKey | b64enc }}
  {{- else }}
  MONGO_REPLICA_SET_KEY: {{ randAlphaNum 756 | b64enc }}
  {{- end }}
{{- end }}
{{- end }}