# Default values specific to the doppler-operator sub-chart.
# These are overridden by the 'dopplerOperator:' section in the umbrella chart's values.

# Note: 'install' is controlled by the umbrella chart condition.

# Example defaults (adjust based on the official Doppler Operator chart or your custom one)
image:
  repository: dopplerhq/doppler-kubernetes-operator
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: "doppler-operator-sa"

# RBAC, resources, nodeSelector, etc. for the operator pod
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {} 