apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Values.knative.serviceName | default (include "common.names.fullname" .) }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    {{- with .Values.knative.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.knative.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  template:
    metadata:
      annotations:
        {{- with .Values.knative.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }} # Use global imagePullSecrets
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort | default 8080 }} 