
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-api-mongodb-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: main-api-mongodb
  template:
    metadata:
      labels:
        app: main-api-mongodb
    spec:
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}  
       
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}  
      containers:
      - name: main-api-mongodb
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.doppler.managedSecretName | default "koci-mongodb-secrets" }} 
              key: MONGO_INITDB_ROOT_USERNAME 
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.doppler.managedSecretName | default "koci-mongodb-secrets" }} 
              key: MONGO_INITDB_ROOT_PASSWORD 
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- end }}
        volumeMounts:
        - name: data-volume
          mountPath: /data/db
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: main-api-mongodb-pvc
          