{{- if .Values.global.doppler.enabled }}
# Doppler Token Secret
# This secret contains the Doppler service token needed for the Doppler Operator
apiVersion: v1
kind: Secret
metadata:
  name: doppler-token-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "koci"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "doppler-token"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    doppler.com/token-secret: "true"
type: Opaque
data:
  # Doppler service token - this should be the actual token value
  # For staging environment
  serviceToken: {{ .Values.doppler.token | b64enc }}
{{- end }} 