{{- if .Values.global.doppler.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.doppler.tokenSecretName }}
  namespace: {{ .Values.global.doppler.operatorNamespace }}
  labels:
    app.kubernetes.io/name: {{ include "common.names.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: doppler-token
type: Opaque
data:
  # Replace with your actual Doppler service token
  serviceToken: {{ required "Doppler token is required" .Values.doppler.token | b64enc }}
{{- end }}