{{- if .Values.doppler.enabled }}
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: {{ include "main-api.fullname" . }}-doppler # Name of the DopplerSecret resource
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "main-api.labels" . | nindent 4 }}
spec:
  # Reference the K8s secret holding the Doppler Service Token
  # This secret must be created *before* deploying the chart (e.g., by deploy.sh)
  tokenSecret:
    name: {{ required "Doppler tokenSecretName is required when doppler is enabled" .Values.doppler.tokenSecretName }}
  # Name of the Kubernetes secret that Doppler Operator will create/manage
  managedSecret:
    name: {{ required "Doppler managedSecretName is required when doppler is enabled" .Values.doppler.managedSecretName }}
  project: {{ required "Doppler projectName is required when doppler is enabled" .Values.doppler.projectName }}
  # Use the global config name unless overridden specifically for this service
  config: {{ .Values.doppler.configName | default .Values.global.dopplerConfigName | required "Doppler configName or global.dopplerConfigName is required" }}
{{- end }} 