apiVersion: v2
name: koci
description: Umbrella chart for deploying the koci infrastructure components (MongoDB, Redis, RabbitMQ, Doppler)
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  # Common templates (always needed)
  - name: common
    repository: file://charts/common
    version: "*"

  # Application Services - ALL DISABLED
  # Note: These are commented out to prevent accidental deployment
  - name: main-api
    repository: file://charts/services/main-api
    version: "*"
    condition: mainApi.enabled

  - name: auth-server
    repository: file://charts/services/auth-server
    version: "*"
    condition: authServer.enabled

  - name: notification-service
    repository: file://charts/services/notification-service
    version: "*"
    condition: notificationService.enabled

  # Databases
  # MySQL - DISABLED (commented out)
  # - name: mysql
  #   repository: file://charts/databases/mysql
  #   version: "*"
  #   condition: global.databases.mysql.selfHosted.enabled

  # MongoDB - ENABLED
  - name: mongodb
    repository: file://charts/databases/mongodb
    version: "*"
    condition: global.databases.mongodb.selfHosted.enabled

  # Jobs
  # MongoDB backup - ENABLED
  - name: mongodb-backup
    repository: file://charts/jobs/mongodb
    version: "*"
    condition: global.databases.mongodb.backup.enabled

  # Cache
  # Redis - ENABLED
  - name: redis
    repository: file://charts/cache/redis
    version: "*"
    condition: global.cache.redis.selfHosted.enabled

  # Messaging
  # RabbitMQ - ENABLED
  - name: rabbitmq
    repository: file://charts/messaging/rabbitmq
    version: "*"
    condition: global.messaging.rabbitmq.selfHosted.enabled

  # Secrets management
  # Doppler Operator - ENABLED
  - name: doppler-kubernetes-operator
    repository: https://helm.doppler.com
    version: "^1.5.0"
    condition: dopplerOperator.install
    alias: doppler-operator

  
  # KNative Functions
  # - name: functions
  #   repository: file://charts/functions
  #   version: "*"
  #   condition: functions.enabled