# Environment: Development
# This file contains development-specific overrides
# Only MongoDB, Redis, RabbitMQ, and Doppler components

global:
  deploymentMode: "local"  
  environment: dev
  storageClass: "standard"
  

    # Image pull secrets for OCI Container Registry
  imagePullSecrets:
    - name: ocir-secret
  
  # OCI Registry configuration
  oci:
    enabled: false
    region: "us-ashburn-1"
    registry:
      server: "yul.ocir.io"


  # Enable Doppler for secrets management
  doppler:
    enabled: true
    project: "oci-infra"
    
    operatorNamespace: "doppler-operator-system"
  
  # Database configuration
  databases:
    # MySQL - DISABLED
    mysql:
      selfHosted:
        enabled: false
      managed:
        enabled: false
    
    # MongoDB - ENABLED with backup
    mongodb:
      selfHosted:
        enabled: true
        replicaCount: 1  
        persistence:
          size: 3Gi  
        auth:
          rootUserSecretKey: MONGO_INITDB_ROOT_USERNAME
          rootPasswordSecretKey: MONGO_INITDB_ROOT_PASSWORD
      backup:
        enabled: true
        schedule: "0 3 * * *"  # Daily backup at 3 AM
        retention: 3  # Keep only 3 days of backups in dev
        storageClass: "standard"
        objectStorage:
          enabled: false  # Disable cloud storage for dev
  
  # Cache configuration
  cache:
    redis:
      selfHosted:
        enabled: true
        persistence:
          size: 1Gi
  
  # Messaging configuration
  messaging:
    rabbitmq:
      selfHosted:
        enabled: true
        persistence:
          size: 1Gi

# Disable all application services
mainApi:
  enabled: false

authServer:
  enabled: false

notificationService:
  enabled: false

# MongoDB configuration for development
mongodb:
  internal:
    enabled: true
  external:
    enabled: false
  # Development-specific MongoDB settings
  image:
    repository: mongo
    tag: "6.0"
    pullPolicy: IfNotPresent
  replicaCount: 1  # Single instance for dev
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  persistence:
    enabled: true
    size: 3Gi
    storageClass: "standard"
  # Development auth settings
  auth:
    enabled: true
    rootUser: "admin"
   

# Redis configuration for development
redis:
  internal:
    enabled: true
  external:
    enabled: false
  # Development-specific Redis settings
  image:
    repository: redis
    tag: "7.0"
    pullPolicy: IfNotPresent
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  persistence:
    enabled: true
    size: 1Gi
    storageClass: "standard"
  # Redis auth
  auth:
    enabled: true
    passwordSecretKey: REDIS_PASSWORD

# RabbitMQ configuration for development
rabbitmq:
  enabled: true
  # Development-specific RabbitMQ settings
  image:
    repository: rabbitmq
    tag: "3.11-management"
    pullPolicy: IfNotPresent
  replicaCount: 1
  cluster:
    replicas: 1
    persistence:
      enabled: true
      storage: 1Gi
      storageClass: "standard"
    auth:
      usernameSecretKey: RABBITMQ_USERNAME
      passwordSecretKey: RABBITMQ_PASSWORD
    service:
      port: 5672
      managementPort: 15672
  connection:
    internal:
      enabled: true
    external:
      enabled: false
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 400m
      memory: 512Mi
  config:
    enableManagement: true  # Enable management UI for dev
    enableMetrics: false
    memoryHighWatermark: 0.4
    diskFreeLimit: "50MB"

# Doppler Operator configuration
dopplerOperator:
  install: true
  image:
    repository: dopplerhq/doppler-kubernetes-operator
    tag: "v1.5.7"
    pullPolicy: IfNotPresent
  serviceAccount:
    create: true
    name: "doppler-operator-sa"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# MongoDB backup job configuration
mongodb-backup:
  enabled: true
  backup:
    image:
      repository: bitnami/mongodb
      tag: "6.0"
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi
  
  # Development backup settings
  global:
    databases:
      mongodb:
        backup:
          enabled: true
          schedule: "0 3 * * *"  # 3 AM daily
          retention: 3  # 3 days retention for dev
          storageClass: "standard"

# Resource defaults for development environment
resources:
  small:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  medium:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 400m
      memory: 512Mi

# Enable persistence for dev environment
persistence:
  enabled: true
  size: 1Gi
  storageClass: "standard"

# Development-specific settings
nodeSelector: {}
tolerations: []
affinity: {}

# Network policies disabled for easier development
networkPolicy:
  enabled: false