apiVersion: v2
name: mongodb
description: Helm chart for deploying MongoDB (internal instance)
type: application # Or 'library' if it only contains helpers/CRDs
version: 0.1.0
# appVersion: "6.0" # Example MongoDB version this chart targets 
dependencies:
  - name: common
    version: "0.1.0"
    repository: "file://../../common" 